resource "gtm_tag" "test_tag_1" {
  name  = "test tag 1"
  type  = "gaawe"
  notes = "Generated by terraform. Do not edit it."
  parameter = [
    {
      key   = "eventName"
      type  = "template"
      value = "event1"
    },
    {
      key  = "eventParameters"
      type = "list"
      list = [{
        type = "map"
        map = [
          {
            type  = "template"
            key   = "name"
            value = "eventName"
          },
          {
            type  = "template"
            key   = "value"
            value = "eventValue"
        }]
      }]
    },
    {
      key   = "measurementId",
      type  = "template"
      value = "G-A2ABC2ABCD"
    }
  ]
  firing_trigger_id = [gtm_trigger.test_trigger_1.id]
}
