# GTM variable
resource "gtm_variable" "test_variable" {
  name  = "test variable"
  type  = "v"
  notes = "Generated by terraform. Do not edit it."
  parameter = [
    {
      key   = "name"
      type  = "template"
      value = "parameters.alpha"
    }
  ]
}
