terraform {
  required_providers {
    gtm = {
      source  = "mirefly/google-tag-manager"
      version = ">= 0.0.8"
    }
  }
}

provider "gtm" {
  credential_file            = "../credentials-77b14e38b4dd.json"
  account_id                 = "6105084028"
  container_id               = "119458552"
  workspace_name             = "my-workspace"
  max_api_queries_per_minute = 15
}

resource "gtm_variable" "test_variable" {
  name  = "test variable"
  type  = "v"
  notes = "Generated by terraform. Do not edit it."
  parameter = [
    {
      key   = "name"
      type  = "template"
      value = "parameters.alpha"
    }
  ]
}

resource "gtm_tag" "test_tag_1" {
  name  = "test tag 1"
  type  = "gaawe"
  notes = "Generated by terraform. Do not edit it."
  parameter = [
    {
      key   = "eventName"
      type  = "template"
      value = "event1"
    },
    {
      key  = "eventParameters"
      type = "list"
      list = [{
        type = "map"
        map = [
          {
            type  = "template"
            key   = "name"
            value = "eventName"
          },
          {
            type  = "template"
            key   = "value"
            value = "eventValue"
        }]
      }]
    },
    {
      key   = "measurementId",
      type  = "template"
      value = "G-A2ABC2ABCD"
    }
  ]
  firing_trigger_id = [gtm_trigger.test_trigger_1.id]
}

resource "gtm_trigger" "test_trigger_1" {
  name = "test trigger 1"
  type = "customEvent"
  custom_event_filter = [
    {
      type = "equals",
      parameter = [
        {
          type  = "template",
          key   = "arg0",
          value = "{{_event}}"
        },
        {
          type  = "template",
          key   = "arg1",
          value = "event-name"
        }
      ]
    }
  ]
}
